### ISSUE TITLE
Buffer limit reached

### ISSUE THREAD

**Issue by a-lucas** [avajs/gulp-ava#19]
When using execFile to execute test, 

That is the error I get when console.logging the stderr.

I suggest to use spawn instead of execFile , because of the bufferLimitation of exec vs spawn.

There is still a bug in spawn buffer, in the case where the output is not captured, which is not our case : https://github.com/nodejs/node/issues/4236

I will probably give you a PR for this fix.

Good job btw :)

```bash
{ Error: stderr maxBuffer exceeded
    at Socket.onChildStderr (child_process.js:282:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:554:20)

```

**Comment by sindresorhus** [comment]
Switching to spawn sounds good. You can use the `maxBuffer` option to increase the max buffer. I think 10 MB should be good.

**Comment by jrsinclair** [comment]
It would be nice if we could find a way to pipe each test response from AVA through line-by-line back to the gulp stream, rather than building up one massive buffer and spitting it out at the end. My gulp-fu is not quite up to the task of figuring that out yet though :-(

**Comment by sindresorhus** [comment]
You can easily do that. Just pipe the process.stdout to https://github.com/maxogden/binary-split to ensure it splits on newlines, then just listen to the `data` event and call `gutil.log` with the data.
