### ISSUE TITLE
Update gulp-util dependency

### ISSUE THREAD

**Issue by samueleishion** [avajs/gulp-ava#27]
`gulp-util` has been deprecated and it causes a warning when running `npm install`:
https://www.npmjs.com/package/gulp-util

```
$ node -v
v12.6.0

$ npm -v 
6.9.0
```

In the context of my project: 
![image](https://user-images.githubusercontent.com/4401818/60638291-6a6a5000-9de3-11e9-86dc-8f2420f38359.png)
![image](https://user-images.githubusercontent.com/4401818/60638300-73f3b800-9de3-11e9-9b03-92d73f0fce35.png)

In the context of `gulp-ava`:
![image](https://user-images.githubusercontent.com/4401818/60638682-f2048e80-9de4-11e9-98b1-0be10bb2fd5a.png)

There is a guide from gulpjs on how to remove this dependency:
https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

It seems, so far in gulp-ava, that the only method used from `gulp-util` is `PluginError`. Could we remove `gulp-util` as a dependency and replace it with `plugin-error` (https://www.npmjs.com/package/plugin-error) as indicated by the guide above?

**Comment by samueleishion** [comment]
Found another instance if `gulp-util` in `test.js`.This time, it uses the `log` method. We would also have to replace it with `fancy-log` (https://www.npmjs.com/package/fancy-log) as indicated in by the guide above.

**Comment by samueleishion** [comment]
I have a branch with the requested updates, but can't push to submit a PR. Is there a way I should request access or at least share the code? 
![image](https://user-images.githubusercontent.com/4401818/60639290-a8697300-9de7-11e9-8a76-68f53123d6b1.png)

**Comment by sindresorhus** [comment]
PR welcome :)

You cannot push directly to this repo. You need to fork it first, and create a PR from your fork.

**Comment by samueleishion** [comment]
@sindresorhus PR updated: https://github.com/avajs/gulp-ava/pull/28

Thanks for the clarification! :)
