### ISSUE TITLE
Stream never ends

### ISSUE THREAD

**Issue by ffMathy** [avajs/gulp-ava#29]
I get the following error in Gulp 4:

> The following tasks did not complete: ava

So I guess it returns a stream that never ends, even when the process dies?

**Comment by ffMathy** [comment]
It might only happen on test failures. Not sure yet.

**Comment by ffMathy** [comment]
In fact, it actually happens on this very repo itself.

Try running `gulp` from the commandline. That error will pop up:

![image](https://user-images.githubusercontent.com/2824010/66510222-e6f08700-ead4-11e9-82b2-bd2c04e0bf6e.png)

**Comment by sindresorhus** [comment]
Fixed by https://github.com/avajs/gulp-ava/pull/31
