### ISSUE TITLE
Gulp throws error with no message on Windows 8

### ISSUE THREAD

**Issue by jamesbrown0** [avajs/gulp-ava#7]
Windows 8. node v5.3.0. gulp v3.9.0. 
If the test file contains no tests or an assertion fails:
`Error: Missing error message
    at new PluginError (x:\Web\solitaire\node_modules\gulp-util\lib\PluginError.js:73:28)`

Otherwise:
`[21:45:31] gulp-ava:`

**Comment by sindresorhus** [comment]
Closing as this is old and probably not a problem anymore.
